=== nvdbleek/com.orbeon.testsuite.w3c/src/tests/test-case.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:runner="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner">
  <xs:element name="test-case">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        
      
		
			  <xs:element name="open">
			    <xs:complexType>
			      <xs:attribute name="href" use="required" type="xs:anyURI"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-title">
			    <xs:complexType>
			      <xs:attribute name="title" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-present">
			    <xs:complexType>
			      <xs:attribute name="type" use="required">
			        <xs:simpleType>
			          <xs:restriction base="xs:token">
			            <xs:enumeration value="input"/>
			            <xs:enumeration value="secret"/>
			            <xs:enumeration value="textarea"/>
			            <xs:enumeration value="output"/>
			            <xs:enumeration value="upload"/>
			            <xs:enumeration value="range"/>
			            <xs:enumeration value="trigger"/>
			            <xs:enumeration value="submit"/>
			            <xs:enumeration value="select"/>
			            <xs:enumeration value="select1"/>
			            <xs:enumeration value="group"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-not-present">
			    <xs:complexType>
			      <xs:attribute name="type" use="required">
			        <xs:simpleType>
			          <xs:restriction base="xs:token">
			            <xs:enumeration value="input"/>
			            <xs:enumeration value="secret"/>
			            <xs:enumeration value="textarea"/>
			            <xs:enumeration value="output"/>
			            <xs:enumeration value="upload"/>
			            <xs:enumeration value="range"/>
			            <xs:enumeration value="trigger"/>
			            <xs:enumeration value="submit"/>
			            <xs:enumeration value="select"/>
			            <xs:enumeration value="select1"/>
			            <xs:enumeration value="group"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-valid">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-invalid">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-readonly">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-readwrite">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-required">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-optional">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-selection-options">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="options" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="select-option">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="option" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="type-input">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="click">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="wait-for-page-to-load" type="xs:string"/>
			  <xs:element name="assert-text-present">
			    <xs:complexType>
			      <xs:attribute name="text" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-text-not-present">
			    <xs:complexType>
			      <xs:attribute name="text" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="fail">
			    <xs:complexType>
			      <xs:attribute name="msg" use="required"/>
			    </xs:complexType>
			  </xs:element>
			</xs:choice>
	    </xs:complexType>
	</xs:element>
</xs:schema>

=== nvdbleek/com.orbeon.testsuite.w3c/src/tests/Chapt03/3.2/3.2.4/3.2.4.b.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner"
           xmlns:xf="http://www.w3.org/2002/xforms"
           xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../../test-case.xsd">
   <open href="Chapt03/3.2/3.2.4/3.2.4.b.xhtml"/>
   <assert-title title="3.2.4.b node-set binding - model attribute of itemset element"/>
   <assert-selection-options locator="xf-select-1" options="Audi,BMW,Mercedes,Porsche,Volkswagen"/>
   <select-option locator="xf-select-1" option="Porsche"/>
   <!-- FIXME select a second option -->
   <click locator="xf-submit-1"/>
   <wait-for-page-to-load/>
   <assert-text-present text="Porsche"/>
</test-case>

=== nvdbleek/com.orbeon.testsuite.w3c/src/tests/Chapt02/2.4.a.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner"
           xmlns:xf="http://www.w3.org/2002/xforms"
           xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../test-case.xsd">
	<open href="Chapt02/2.4.a.xhtml"/>
	<assert-title title="2.4.a Example: Multiple Forms"/>
	<assert-selection-options locator="xf-select1-1" options="Cash,Credit" />
	<assert-control-present locator="xf-input-1" type="input" />
	<assert-control-present locator="xf-input-2" type="input" />
	<select-option locator="xf-select1-1" option="Cash"/>
	<assert-control-not-present locator="xf-input-1" type="input" />
	<assert-control-not-present locator="xf-input-2" type="input" />
	<click locator="xf-submit-1" />
	<wait-for-page-to-load />
	<assert-title title="Results from echo.sh" />
	<assert-text-present text="method=&quot;cash&quot;" />
	<assert-text-not-present text="&lt;number" />
	<assert-text-not-present text="&lt;expiry" />
	<assert-text-not-present text="helpful" />
	
	<open href="Chapt02/2.4.a.xhtml"/>
	<assert-title title="2.4.a Example: Multiple Forms"/>
	<type-input locator="xf-input-1" value="4012888888881881" />
	<type-input locator="xf-input-2" value="2001" />
	<click locator="xf-submit-1" />
	<assert-control-invalid locator="xf-input-2"/>
	<type-input locator="xf-input-2" value="2001-08" />
	<click locator="xf-submit-1" />
	<wait-for-page-to-load />
	<assert-title title="Results from echo.sh" />
	<assert-text-present text="method=&quot;cc&quot;" />
	<assert-text-present text="&lt;number&gt;4012888888881881&lt;/number&gt;" />
	<assert-text-present text="&lt;expiry&gt;2001-08&lt;/expiry&gt;" /> 
	<assert-text-not-present text="helpful" />
	
	<open href="Chapt02/2.4.a.xhtml"/>
	<assert-title title="2.4.a Example: Multiple Forms"/>
	<assert-selection-options locator="xf-select1-2" options="Not at all helpful (0),Barely helpful (1),Somewhat helpful (2),Very helpful (3)" />
	<click locator="xf-submit-2" />
	<wait-for-page-to-load />
	<assert-title title="Results from echo.sh" />
	<assert-text-present text="&lt;helpful&gt;3&lt;/helpful&gt;" />
	<assert-text-not-present text="method" />
	
</test-case>

=== nvdbleek/com.orbeon.testsuite.w3c/src/tests/Chapt07/7.8/7.8.4/7.8.4.a.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner"
           xmlns:xf="http://www.w3.org/2002/xforms"
           xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../../test-case.xsd">
   <open href="Chapt07/7.8/7.8.4/7.8.4.a.xhtml"/>
   <assert-title title="7.8.4.a hmac() function using sha1, md5, and sha256"/>
   <assert-control-present locator="xf-group-3" type="group"/>
   <assert-control-not-present locator="xf-group-5" type="group"/>
   <assert-control-present locator="xf-group-6" type="group"/>
   <assert-control-not-present locator="xf-group-8" type="group"/>
   <assert-control-present locator="xf-group-9" type="group"/>
   <assert-control-not-present locator="xf-group-11" type="group"/>
   <assert-control-present locator="xf-group-12" type="group"/>
   <assert-control-not-present locator="xf-group-14" type="group"/>
   <assert-control-present locator="xf-group-15" type="group"/>
   <assert-control-not-present locator="xf-group-17" type="group"/>
   <assert-control-present locator="xf-group-18" type="group"/>
   <assert-control-not-present locator="xf-group-20" type="group"/>
</test-case>

=== nvdbleek/com.orbeon.testsuite.w3c/src/tests/Chapt02/2.2.a.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner"
           xmlns:xf="http://www.w3.org/2002/xforms"
           xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../test-case.xsd">
    <open href="Chapt02/2.2.a.xhtml"/>
    <assert-title title="2.2.a Example: Encapsulation of Instance Data"/>
    <assert-selection-options locator="xf-select1-1" options="Cash,Credit" />
	<assert-control-present locator="xf-input-1" type="input" />
	<assert-control-present locator="xf-input-2" type="input" />
	<type-input locator="xf-input-1" value="4012888888881881" />
	<type-input locator="xf-input-2" value="2001-08" />
	<click locator="xf-submit-1" />
	<wait-for-page-to-load />
	<assert-title title="Results from echo.sh" />
	<assert-text-present text="method=&quot;cc&quot;" />
	<assert-text-present text="&lt;number&gt;4012888888881881&lt;/number&gt;" />
	<assert-text-present text="&lt;expiry&gt;2001-08&lt;/expiry&gt;" />
	   
    <open href="Chapt02/2.2.a.xhtml"/>
    <assert-title title="2.2.a Example: Encapsulation of Instance Data"/>
	<select-option locator="xf-select1-1" option="Cash"/>
	<click locator="xf-submit-1" />
	<wait-for-page-to-load />
	<assert-title title="Results from echo.sh" />
	<assert-text-present text="method=&quot;cash&quot;" />
	<assert-text-present text="&lt;number/&gt;" />
	<assert-text-present text="&lt;expiry/&gt;" />
</test-case>
